export const UPDATE_CURRENT_USER_PROFILE_REQUEST = 'UPDATE_CURRENT_USER_PROFILE_REQUEST';
export const UPDATE_CURRENT_USER_PROFILE_SUCCESS = 'UPDATE_CURRENT_USER_REQUEST_SUCCESS';
export const UPDATE_CURRENT_USER_PROFILE_ERROR = 'UPDATE_CURRENT_USER_REQUEST_ERROR';

export const DELETE_CURRENT_USER_PROFILE_REQUEST = 'DELETE_CURRENT_USER_PROFILE_REQUEST';
export const DELETE_CURRENT_USER_PROFILE_SUCCESS = 'DELETE_CURRENT_USER_PROFILE_SUCCESS';
export const DELETE_CURRENT_USER_PROFILE_ERROR = 'DELETE_CURRENT_USER_PROFILE_ERROR';

export const UPDATE_CURRENT_USER_EMAIL_REQUEST = 'UPDATE_CURRENT_USER_EMAIL_REQUEST';
export const UPDATE_CURRENT_USER_EMAIL_SUCCESS = 'UPDATE_CURRENT_USER_EMAIL_SUCCESS';
export const UPDATE_CURRENT_USER_EMAIL_ERROR = 'UPDATE_CURRENT_USER_EMAIL_ERROR';

export const UPDATE_CURRENT_USER_PASSWORD_REQUEST = 'UPDATE_CURRENT_USER_PASSWORD_REQUEST';
export const UPDATE_CURRENT_USER_PASSWORD_SUCCESS = 'UPDATE_CURRENT_USER_PASSWORD_SUCCESS';
export const UPDATE_CURRENT_USER_PASSWORD_ERROR = 'UPDATE_CURRENT_USER_PASSWORD_ERROR';
