export const CREATE_SHORTLIST_ITEM_REQUEST = 'CREATE_SHORTLIST_ITEM_REQUEST';
export const CREATE_SHORTLIST_ITEM_SUCCESS = 'CREATE_SHORTLIST_ITEM_SUCCESS';
export const CREATE_SHORTLIST_ITEM_ERROR = 'CREATE_SHORTLIST_ITEM_ERROR';
export const DELETE_SHORTLIST_ITEM_REQUEST = 'DELETE_SHORTLIST_ITEM_REQUEST';
export const DELETE_SHORTLIST_ITEM_SUCCESS = 'DELETE_SHORTLIST_ITEM_SUCCESS';
export const DELETE_SHORTLIST_ITEM_ERROR = 'DELETE_SHORTLIST_ITEM_ERROR';
