export const FETCH_CURRENT_USER_PROFILE_REQUEST = 'FETCH_CURRENT_USER_PROFILE_REQUEST';
export const FETCH_CURRENT_USER_PROFILE_SUCCESS = 'FETCH_CURRENT_USER_PROFILE_SUCCESS';
export const FETCH_CURRENT_USER_PROFILE_ERROR = 'FETCH_CURRENT_USER_PROFILE_ERROR';
