export const FETCH_FLATMATES_REQUEST = 'FETCH_FLATMATES_REQUEST';
export const FETCH_FLATMATES_SUCCESS = 'FETCH_FLATMATES_SUCCESS';
export const FETCH_FLATMATES_ERROR = 'FETCH_FLATMATES_ERROR';
export const FETCH_SINGLE_FLATMATE = 'FETCH_SINGLE_FLATMATE';
